name = "yabu"
main = "worker/index.ts"
compatibility_date = "2025-06-03"

[vars]
SUPABASE_URL = "https://pmajmgryddjdgstpfcfn.supabase.co"
SUPABASE_ANON_KEY = "sb_publishable_79EA0ZPrGuZRJpSf-raCIg_0nAWWINV"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "yabusunnyday"
